language: php
php:
  - 5.5
  - 5.6
before_script:
  ## Composer
  - composer install
  ## Travis configuration
  - cp config/settings.inc.php.ini config/settings.inc.php
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l10n-tools"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "%{repository} ; %{commit} (%{author}) : %{message} "
      - "Build details: %{build_url} ; changes: %{compare_url}"
