sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache/files
php:
  - 7.0
  - 7.2
  - 7.3
before_install:
  ## Install latest version of node
  - nvm install node
  ## Disabling xdebug
  - phpenv config-rm xdebug.ini
install:
  # Update composer, install dependencies
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - composer self-update
  - composer install $flags
  ## Install ESLint
  - npm install -g eslint
before_script:
  ## Travis configuration
  - cp app/config/settings.inc.php.ini app/config/settings.inc.php
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/ --use-light-report
  - php tests/functional/api.php
  - php tests/integrity/source_integrity.php
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - eslint web/assets/js
